package com.yousoft.cfapi.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Newsdetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.NEWSDETAIL.TEXTID
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	private BigDecimal textid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.NEWSDETAIL.USERSRC
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	private String usersrc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.NEWSDETAIL.USERDEST
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	private String userdest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.NEWSDETAIL.NEWSTYPE
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	private BigDecimal newstype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.NEWSDETAIL.CONTENT
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.NEWSDETAIL.CREATETIME
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	private Date createtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.NEWSDETAIL.TEXTID
	 * @return  the value of API.NEWSDETAIL.TEXTID
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public BigDecimal getTextid() {
		return textid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.NEWSDETAIL.TEXTID
	 * @param textid  the value for API.NEWSDETAIL.TEXTID
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public void setTextid(BigDecimal textid) {
		this.textid = textid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.NEWSDETAIL.USERSRC
	 * @return  the value of API.NEWSDETAIL.USERSRC
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public String getUsersrc() {
		return usersrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.NEWSDETAIL.USERSRC
	 * @param usersrc  the value for API.NEWSDETAIL.USERSRC
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public void setUsersrc(String usersrc) {
		this.usersrc = usersrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.NEWSDETAIL.USERDEST
	 * @return  the value of API.NEWSDETAIL.USERDEST
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public String getUserdest() {
		return userdest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.NEWSDETAIL.USERDEST
	 * @param userdest  the value for API.NEWSDETAIL.USERDEST
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public void setUserdest(String userdest) {
		this.userdest = userdest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.NEWSDETAIL.NEWSTYPE
	 * @return  the value of API.NEWSDETAIL.NEWSTYPE
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public BigDecimal getNewstype() {
		return newstype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.NEWSDETAIL.NEWSTYPE
	 * @param newstype  the value for API.NEWSDETAIL.NEWSTYPE
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public void setNewstype(BigDecimal newstype) {
		this.newstype = newstype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.NEWSDETAIL.CONTENT
	 * @return  the value of API.NEWSDETAIL.CONTENT
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.NEWSDETAIL.CONTENT
	 * @param content  the value for API.NEWSDETAIL.CONTENT
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.NEWSDETAIL.CREATETIME
	 * @return  the value of API.NEWSDETAIL.CREATETIME
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.NEWSDETAIL.CREATETIME
	 * @param createtime  the value for API.NEWSDETAIL.CREATETIME
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
}