package com.yousoft.cfapi.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Pubcontent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.PUBCONTENT.CTID
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    private BigDecimal ctid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.PUBCONTENT.TEXT
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.PUBCONTENT.PHOTO
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.PUBCONTENT.URL
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.PUBCONTENT.PUBUID
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    private String pubuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.PUBCONTENT.PUBTIME
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    private Date pubtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.PUBCONTENT.ZANCOUNT
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    private BigDecimal zancount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.PUBCONTENT.PLCOUNT
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    private BigDecimal plcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.PUBCONTENT.CTID
     *
     * @return the value of API.PUBCONTENT.CTID
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public BigDecimal getCtid() {
        return ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.PUBCONTENT.CTID
     *
     * @param ctid the value for API.PUBCONTENT.CTID
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public void setCtid(BigDecimal ctid) {
        this.ctid = ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.PUBCONTENT.TEXT
     *
     * @return the value of API.PUBCONTENT.TEXT
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.PUBCONTENT.TEXT
     *
     * @param text the value for API.PUBCONTENT.TEXT
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.PUBCONTENT.PHOTO
     *
     * @return the value of API.PUBCONTENT.PHOTO
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.PUBCONTENT.PHOTO
     *
     * @param photo the value for API.PUBCONTENT.PHOTO
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.PUBCONTENT.URL
     *
     * @return the value of API.PUBCONTENT.URL
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.PUBCONTENT.URL
     *
     * @param url the value for API.PUBCONTENT.URL
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.PUBCONTENT.PUBUID
     *
     * @return the value of API.PUBCONTENT.PUBUID
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public String getPubuid() {
        return pubuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.PUBCONTENT.PUBUID
     *
     * @param pubuid the value for API.PUBCONTENT.PUBUID
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public void setPubuid(String pubuid) {
        this.pubuid = pubuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.PUBCONTENT.PUBTIME
     *
     * @return the value of API.PUBCONTENT.PUBTIME
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public Date getPubtime() {
        return pubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.PUBCONTENT.PUBTIME
     *
     * @param pubtime the value for API.PUBCONTENT.PUBTIME
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public void setPubtime(Date pubtime) {
        this.pubtime = pubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.PUBCONTENT.ZANCOUNT
     *
     * @return the value of API.PUBCONTENT.ZANCOUNT
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public BigDecimal getZancount() {
        return zancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.PUBCONTENT.ZANCOUNT
     *
     * @param zancount the value for API.PUBCONTENT.ZANCOUNT
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public void setZancount(BigDecimal zancount) {
        this.zancount = zancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.PUBCONTENT.PLCOUNT
     *
     * @return the value of API.PUBCONTENT.PLCOUNT
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public BigDecimal getPlcount() {
        return plcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.PUBCONTENT.PLCOUNT
     *
     * @param plcount the value for API.PUBCONTENT.PLCOUNT
     *
     * @mbggenerated Sun Jun 28 23:28:44 CST 2015
     */
    public void setPlcount(BigDecimal plcount) {
        this.plcount = plcount;
    }
}