package com.yousoft.cfapi.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RelationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public RelationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserfromIsNull() {
			addCriterion("USERFROM is null");
			return (Criteria) this;
		}

		public Criteria andUserfromIsNotNull() {
			addCriterion("USERFROM is not null");
			return (Criteria) this;
		}

		public Criteria andUserfromEqualTo(String value) {
			addCriterion("USERFROM =", value, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromNotEqualTo(String value) {
			addCriterion("USERFROM <>", value, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromGreaterThan(String value) {
			addCriterion("USERFROM >", value, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromGreaterThanOrEqualTo(String value) {
			addCriterion("USERFROM >=", value, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromLessThan(String value) {
			addCriterion("USERFROM <", value, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromLessThanOrEqualTo(String value) {
			addCriterion("USERFROM <=", value, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromLike(String value) {
			addCriterion("USERFROM like", value, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromNotLike(String value) {
			addCriterion("USERFROM not like", value, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromIn(List<String> values) {
			addCriterion("USERFROM in", values, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromNotIn(List<String> values) {
			addCriterion("USERFROM not in", values, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromBetween(String value1, String value2) {
			addCriterion("USERFROM between", value1, value2, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUserfromNotBetween(String value1, String value2) {
			addCriterion("USERFROM not between", value1, value2, "userfrom");
			return (Criteria) this;
		}

		public Criteria andUsertoIsNull() {
			addCriterion("USERTO is null");
			return (Criteria) this;
		}

		public Criteria andUsertoIsNotNull() {
			addCriterion("USERTO is not null");
			return (Criteria) this;
		}

		public Criteria andUsertoEqualTo(String value) {
			addCriterion("USERTO =", value, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoNotEqualTo(String value) {
			addCriterion("USERTO <>", value, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoGreaterThan(String value) {
			addCriterion("USERTO >", value, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoGreaterThanOrEqualTo(String value) {
			addCriterion("USERTO >=", value, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoLessThan(String value) {
			addCriterion("USERTO <", value, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoLessThanOrEqualTo(String value) {
			addCriterion("USERTO <=", value, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoLike(String value) {
			addCriterion("USERTO like", value, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoNotLike(String value) {
			addCriterion("USERTO not like", value, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoIn(List<String> values) {
			addCriterion("USERTO in", values, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoNotIn(List<String> values) {
			addCriterion("USERTO not in", values, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoBetween(String value1, String value2) {
			addCriterion("USERTO between", value1, value2, "userto");
			return (Criteria) this;
		}

		public Criteria andUsertoNotBetween(String value1, String value2) {
			addCriterion("USERTO not between", value1, value2, "userto");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table API.RELATION
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table API.RELATION
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 30 11:46:50 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}