package com.yousoft.cfapi.entity;


public class Relation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.RELATION.USERFROM
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	private String userfrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.RELATION.USERTO
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	private String userto;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.RELATION.USERFROM
	 * @return  the value of API.RELATION.USERFROM
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public String getUserfrom() {
		return userfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.RELATION.USERFROM
	 * @param userfrom  the value for API.RELATION.USERFROM
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public void setUserfrom(String userfrom) {
		this.userfrom = userfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.RELATION.USERTO
	 * @return  the value of API.RELATION.USERTO
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public String getUserto() {
		return userto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.RELATION.USERTO
	 * @param userto  the value for API.RELATION.USERTO
	 * @mbggenerated  Tue Jun 30 13:23:47 CST 2015
	 */
	public void setUserto(String userto) {
		this.userto = userto;
	}
}