package com.yousoft.cfapi.entity;

public class Relation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.RELATION.USERFROM
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    private String userfrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.RELATION.USERTO
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    private String userto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.RELATION.FLAG1
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    private String flag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.RELATION.FLAG2
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    private String flag2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.RELATION.USERFROM
     *
     * @return the value of API.RELATION.USERFROM
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    public String getUserfrom() {
        return userfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.RELATION.USERFROM
     *
     * @param userfrom the value for API.RELATION.USERFROM
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    public void setUserfrom(String userfrom) {
        this.userfrom = userfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.RELATION.USERTO
     *
     * @return the value of API.RELATION.USERTO
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    public String getUserto() {
        return userto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.RELATION.USERTO
     *
     * @param userto the value for API.RELATION.USERTO
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    public void setUserto(String userto) {
        this.userto = userto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.RELATION.FLAG1
     *
     * @return the value of API.RELATION.FLAG1
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    public String getFlag1() {
        return flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.RELATION.FLAG1
     *
     * @param flag1 the value for API.RELATION.FLAG1
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.RELATION.FLAG2
     *
     * @return the value of API.RELATION.FLAG2
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.RELATION.FLAG2
     *
     * @param flag2 the value for API.RELATION.FLAG2
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
}