package com.yousoft.cfapi.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Replydetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.REPLYDETAIL.TEXTID
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    private BigDecimal textid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.REPLYDETAIL.REPLY
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    private String reply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.REPLYDETAIL.USERFROM
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    private String userfrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.REPLYDETAIL.USERTO
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    private String userto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.REPLYDETAIL.REPLYTYPE
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    private BigDecimal replytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column API.REPLYDETAIL.REPLYTIME
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    private Date replytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.REPLYDETAIL.TEXTID
     *
     * @return the value of API.REPLYDETAIL.TEXTID
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public BigDecimal getTextid() {
        return textid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.REPLYDETAIL.TEXTID
     *
     * @param textid the value for API.REPLYDETAIL.TEXTID
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public void setTextid(BigDecimal textid) {
        this.textid = textid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.REPLYDETAIL.REPLY
     *
     * @return the value of API.REPLYDETAIL.REPLY
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.REPLYDETAIL.REPLY
     *
     * @param reply the value for API.REPLYDETAIL.REPLY
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public void setReply(String reply) {
        this.reply = reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.REPLYDETAIL.USERFROM
     *
     * @return the value of API.REPLYDETAIL.USERFROM
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public String getUserfrom() {
        return userfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.REPLYDETAIL.USERFROM
     *
     * @param userfrom the value for API.REPLYDETAIL.USERFROM
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public void setUserfrom(String userfrom) {
        this.userfrom = userfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.REPLYDETAIL.USERTO
     *
     * @return the value of API.REPLYDETAIL.USERTO
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public String getUserto() {
        return userto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.REPLYDETAIL.USERTO
     *
     * @param userto the value for API.REPLYDETAIL.USERTO
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public void setUserto(String userto) {
        this.userto = userto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.REPLYDETAIL.REPLYTYPE
     *
     * @return the value of API.REPLYDETAIL.REPLYTYPE
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public BigDecimal getReplytype() {
        return replytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.REPLYDETAIL.REPLYTYPE
     *
     * @param replytype the value for API.REPLYDETAIL.REPLYTYPE
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public void setReplytype(BigDecimal replytype) {
        this.replytype = replytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column API.REPLYDETAIL.REPLYTIME
     *
     * @return the value of API.REPLYDETAIL.REPLYTIME
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column API.REPLYDETAIL.REPLYTIME
     *
     * @param replytime the value for API.REPLYDETAIL.REPLYTIME
     *
     * @mbggenerated Tue Jun 30 11:46:27 CST 2015
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }
}