package com.yousoft.cfapi.entity;

import java.math.BigDecimal;

public class Zandetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.ZANDETAIL.TEXTID
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	private BigDecimal textid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.ZANDETAIL.USERNAME
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column API.ZANDETAIL.USERID
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	private String userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.ZANDETAIL.TEXTID
	 * @return  the value of API.ZANDETAIL.TEXTID
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	public BigDecimal getTextid() {
		return textid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.ZANDETAIL.TEXTID
	 * @param textid  the value for API.ZANDETAIL.TEXTID
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	public void setTextid(BigDecimal textid) {
		this.textid = textid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.ZANDETAIL.USERNAME
	 * @return  the value of API.ZANDETAIL.USERNAME
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.ZANDETAIL.USERNAME
	 * @param username  the value for API.ZANDETAIL.USERNAME
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column API.ZANDETAIL.USERID
	 * @return  the value of API.ZANDETAIL.USERID
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column API.ZANDETAIL.USERID
	 * @param userid  the value for API.ZANDETAIL.USERID
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}
}