-- 创建内容发布表
CREATE TABLE PUBCONTENT (
	CTID INTEGER NOT NULL PRIMARY KEY,
	TEXT VARCHAR2(500),
	PHOTO VARCHAR2(500),
	URL VARCHAR2(500),
	PUBUID VARCHAR2(32),
	PUBTIME DATE,
	ZANCOUNT INTEGER,
	PLCOUNT INTEGER
);
-- 添加对表的描述信息
COMMENT ON TABLE PUBCONTENT IS '朋友圈发布表';
COMMENT ON COLUMN PUBCONTENT.CTID IS '发布内容ID';
COMMENT ON COLUMN PUBCONTENT.TEXT IS '发布文本内容';
COMMENT ON COLUMN PUBCONTENT.PHOTO IS '发布照片列表(以逗号隔开)';
COMMENT ON COLUMN PUBCONTENT.URL IS '转发链接请求URL';
COMMENT ON COLUMN PUBCONTENT.PUBUID IS '发布者用户ID';
COMMENT ON COLUMN PUBCONTENT.PUBTIME IS '内容发布时间';
COMMENT ON COLUMN PUBCONTENT.ZANCOUNT IS '点赞人数';
COMMENT ON COLUMN PUBCONTENT.PLCOUNT IS '评论人数';
-- 添加索引
CREATE INDEX IDX_PUBCONTENT_PUBUID ON PUBCONTENT(PUBUID);
CREATE INDEX IDX_PUBCONTENT_PUTTIME ON PUBCONTENT(PUBTIME);


-- 创建用户关联关系表(存放好友信息,是否对方屏蔽等)
CREATE TABLE RELATION (
	USERFROM VARCHAR2(32) NOT NULL,
	USERTO VARCHAR2(32) NOT NULL,
	FLAG1 CHAR(1) DEFAULT '0' NOT NULL,
	FLAG2 CHAR(1) DEFAULT '0' NOT NULL
);
-- 添加注释信息
COMMENT ON TABLE RELATION IS '用户关联信息表';
COMMENT ON COLUMN RELATION.USERFROM IS '主动者';
COMMENT ON COLUMN RELATION.USERTO IS '被动者';
COMMENT ON COLUMN RELATION.FLAG1 IS '不看对方朋友圈标识';
COMMENT ON COLUMN RELATION.FLAG2 IS '不让对方看自己的消息标识';

-- 添加索引
CREATE INDEX IDX_RELATION_USERFROM ON RELATION(USERFROM);
CREATE INDEX IDX_RELATION_USERTO ON RELATION(USERTO);


-- 回复评论表
CREATE TABLE REPLYDETAIL(
	TEXTID INTEGER NOT NULL,
	REPLY VARCHAR2(500),
	USERFROM VARCHAR2(32),
	USERTO VARCHAR2(32),
	REPLYTYPE INTEGER,
	REPLYTIME DATE
);

-- 添加注释信息
COMMENT ON TABLE REPLYDETAIL IS '回复评论表';
COMMENT ON COLUMN REPLYDETAIL.TEXTID IS '消息ID';
COMMENT ON COLUMN REPLYDETAIL.REPLY IS '回复/评论内容';
COMMENT ON COLUMN REPLYDETAIL.USERFROM IS '回复/评论者ID';
COMMENT ON COLUMN REPLYDETAIL.USERTO IS '被回复者ID/评论时留空';
COMMENT ON COLUMN REPLYDETAIL.REPLYTYPE IS '消息类型0评论1回复';
COMMENT ON COLUMN REPLYDETAIL.REPLYTIME IS '评论回复时间';

-- 添加索引
CREATE INDEX IDX_REPLYDETAIL_REPLYTIME ON REPLYDETAIL(REPLYTIME);
CREATE INDEX IDX_REPLYDETAIL_USERTO ON REPLYDETAIL(USERTO);


CREATE TABLE ZANDETAIL(
	TEXTID INTEGER NOT NULL,
	USERNAME VARCHAR2(32),
	USERID VARCHAR2(32)
);

-- 添加注释信息
COMMENT ON TABLE ZANDETAIL IS '点赞表';
COMMENT ON COLUMN ZANDETAIL.TEXTID IS '消息ID';
COMMENT ON COLUMN ZANDETAIL.USERNAME IS '点赞者昵称';
COMMENT ON COLUMN ZANDETAIL.USERFROM IS '点赞者ID';



CREATE TABLE NEWSDETAIL(
	TEXTID INTEGER NOT NULL,
	USERSRC VARCHAR2(32),
	USERDEST VARCHAR2(32),
	NEWSTYPE INTEGER,
	CONTENT VARCHAR2(500),
	CREATETIME DATE DEFAULT SYSDATE
);

COMMENT ON TABLE NEWSDETAIL IS '新消息明细表';
COMMENT ON COLUMN NEWSDETAIL.TEXTID IS '消息ID';
COMMENT ON COLUMN NEWSDETAIL.USERSRC IS '消息发布源';
COMMENT ON COLUMN NEWSDETAIL.USERDEST IS '消息接收者ID';
COMMENT ON COLUMN NEWSDETAIL.NEWSTYPE IS '消息类型';
COMMENT ON COLUMN NEWSDETAIL.CONTENT IS '消息内容';

CREATE INDEX IDX_NEWSDETAIL_USERSRC ON NEWSDETAIL(USERSRC);
CREATE INDEX IDX_NEWSDETAIL_USERDEST ON NEWSDETAIL(USERDEST);
CREATE INDEX IDX_NEWSDETAIL_CREATETIME ON NEWSDETAIL(CREATETIME);
