package com.yousoft.cfapi.dao;

import com.yousoft.cfapi.entity.Newsdetail;
import com.yousoft.cfapi.entity.NewsdetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsdetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.NEWSDETAIL
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	int countByExample(NewsdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.NEWSDETAIL
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	int deleteByExample(NewsdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.NEWSDETAIL
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	int insert(Newsdetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.NEWSDETAIL
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	int insertSelective(Newsdetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.NEWSDETAIL
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	List<Newsdetail> selectByExample(NewsdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.NEWSDETAIL
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Newsdetail record,
			@Param("example") NewsdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.NEWSDETAIL
	 * @mbggenerated  Thu Jul 02 15:37:39 CST 2015
	 */
	int updateByExample(@Param("record") Newsdetail record,
			@Param("example") NewsdetailExample example);
}