package com.yousoft.cfapi.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.yousoft.cfapi.entity.Pubcontent;
import com.yousoft.cfapi.entity.PubcontentExample;

@Repository
public interface PubcontentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	int countByExample(PubcontentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	int deleteByExample(PubcontentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal ctid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	int insert(Pubcontent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	int insertSelective(Pubcontent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	List<Pubcontent> selectByExample(PubcontentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	Pubcontent selectByPrimaryKey(BigDecimal ctid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Pubcontent record,
			@Param("example") PubcontentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	int updateByExample(@Param("record") Pubcontent record,
			@Param("example") PubcontentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	int updateByPrimaryKeySelective(Pubcontent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.PUBCONTENT
	 * 
	 * @mbggenerated Sun Jun 28 23:28:44 CST 2015
	 */
	int updateByPrimaryKey(Pubcontent record);

	/**
	 * 分页查询发布的列表内容
	 * 
	 * @return
	 */
	List<Pubcontent> findContentByPage(@Param("userid") String userid,
			@Param("pagestart") Integer pagestart,
			@Param("pageend") Integer pageend);

	/**
	 * 根据发布用户查看其发布内容列表
	 * 
	 * @param userid
	 *            用户ID
	 * @return
	 */
	List<Pubcontent> findContentByUserId(@Param("userid") String userid,
			@Param("pagestart") Integer pagestart,
			@Param("pageend") Integer pageend);
	
	/**
	 * 根据文本ID查询发布对象
	 * @param textid 文本ID
	 * @return
	 */
	Pubcontent findContentByTextId(@Param("textid") Integer textid);
}