package com.yousoft.cfapi.dao;

import com.yousoft.cfapi.entity.Relation;
import com.yousoft.cfapi.entity.RelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API.RELATION
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    int countByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API.RELATION
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    int deleteByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API.RELATION
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    int insert(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API.RELATION
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    int insertSelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API.RELATION
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    List<Relation> selectByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API.RELATION
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    int updateByExampleSelective(@Param("record") Relation record, @Param("example") RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API.RELATION
     *
     * @mbggenerated Sat Jul 04 17:10:18 CST 2015
     */
    int updateByExample(@Param("record") Relation record, @Param("example") RelationExample example);
}