package com.yousoft.cfapi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yousoft.cfapi.entity.Replydetail;
import com.yousoft.cfapi.entity.ReplydetailExample;
import com.yousoft.cfapi.entity.model.PlView;

public interface ReplydetailMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.REPLYDETAIL
	 *
	 * @mbggenerated Tue Jun 30 11:46:27 CST 2015
	 */
	int countByExample(ReplydetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.REPLYDETAIL
	 *
	 * @mbggenerated Tue Jun 30 11:46:27 CST 2015
	 */
	int deleteByExample(ReplydetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.REPLYDETAIL
	 *
	 * @mbggenerated Tue Jun 30 11:46:27 CST 2015
	 */
	int insert(Replydetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.REPLYDETAIL
	 *
	 * @mbggenerated Tue Jun 30 11:46:27 CST 2015
	 */
	int insertSelective(Replydetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.REPLYDETAIL
	 *
	 * @mbggenerated Tue Jun 30 11:46:27 CST 2015
	 */
	List<Replydetail> selectByExample(ReplydetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.REPLYDETAIL
	 *
	 * @mbggenerated Tue Jun 30 11:46:27 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Replydetail record,
			@Param("example") ReplydetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table API.REPLYDETAIL
	 *
	 * @mbggenerated Tue Jun 30 11:46:27 CST 2015
	 */
	int updateByExample(@Param("record") Replydetail record,
			@Param("example") ReplydetailExample example);

	List<PlView> findPlViewListByTextId(@Param("textid") Integer textid,
			@Param("userid") String userid);
}