package com.yousoft.cfapi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yousoft.cfapi.entity.Zandetail;
import com.yousoft.cfapi.entity.ZandetailExample;

public interface ZandetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.ZANDETAIL
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	int countByExample(ZandetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.ZANDETAIL
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	int deleteByExample(ZandetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.ZANDETAIL
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	int insert(Zandetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.ZANDETAIL
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	int insertSelective(Zandetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.ZANDETAIL
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	List<Zandetail> selectByExample(ZandetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.ZANDETAIL
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Zandetail record,
			@Param("example") ZandetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table API.ZANDETAIL
	 * @mbggenerated  Tue Jun 30 11:49:46 CST 2015
	 */
	int updateByExample(@Param("record") Zandetail record,
			@Param("example") ZandetailExample example);
	
	
	List<String> findZanListByTextId(@Param("textid") Integer textid);
}